all: 
    hosts:
    children:   # key order does not matter, indentation does
        acme:
            children:
                dev:
                eap:
                webserver:
                app1: 
                app2: 
                app3: 

