all: 
    hosts:
    children:   # key order does not matter, indentation does
        acme:
            children:
                dev:
                eap:
                webserver:
        dev:
        eap: 
        webserver: 

