all: 
    hosts:
    children:   # key order does not matter, indentation does
        acme:
            children:
                services: 
                  app1:        
                roles: 
                  dev:
                  eap:
                  webserver:

