global_context: movie_machine

vmw_project: terminator
vmw_role: webserver
vmw_env: demo
vmw_service: app1
vmw_count: 1

app: 
  app_name: terminator_v1
  app_config: give me your boots, your gun, and your motorcycle
  
